
platform :ios, '9.0'

target 'DataSiswaIDN' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.5.1'
  pod 'SwiftyJSON', '~> 4.0.0'

  # Pods for DataSiswaIDN

  target 'DataSiswaIDNTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DataSiswaIDNUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
